# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [2]:
import torch

In [3]:
torch.__version__

'1.8.1+cpu'

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [4]:
arr = torch.zeros(8, 8)

In [5]:
first_line = torch.Tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
arr[0, 0:8], arr[7, 0:8] = first_line, -first_line

In [6]:
arr[1, 0:8], arr[6, 0:8] = -torch.ones(1, 8), torch.ones(1, 8)

In [7]:
arr

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [8]:
torch.Tensor([i for i in range(2, 21) if i % 2 == 0]) * torch.Tensor([i for i in range(2, 22) if i % 2 == 1])

tensor([  6.,  20.,  42.,  72., 110., 156., 210., 272., 342., 420.])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [9]:
torch.Tensor([[i + j * 10 for i in range(1, 8)] for j in range(11)])

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.],
        [ 41.,  42.,  43.,  44.,  45.,  46.,  47.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.],
        [ 81.,  82.,  83.,  84.,  85.,  86.,  87.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.],
        [101., 102., 103., 104., 105., 106., 107.]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [10]:
def func(n, m):
    return torch.Tensor([[2, 3] * n if j % 2 == 1 else [0, 1] * n for j in range(m)])[:, 0:m]

In [11]:
func(4, 5)

tensor([[0., 1., 0., 1., 0.],
        [2., 3., 2., 3., 2.],
        [0., 1., 0., 1., 0.],
        [2., 3., 2., 3., 2.],
        [0., 1., 0., 1., 0.]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [12]:
t = torch.FloatTensor(4, 7).uniform_(0, 20)

In [13]:
t

tensor([[ 4.6562,  1.5647, 11.0971,  9.3681, 16.7583, 13.1306,  1.2198],
        [14.5332,  8.2005, 16.9029, 14.2904,  8.6099,  0.0443,  4.6798],
        [14.6739, 11.1202,  6.8576,  4.8135, 16.4704, 17.4471, 11.3121],
        [10.6834, 12.6290,  0.2992, 10.0702,  3.3553, 11.6600, 16.8390]])

In [14]:
t = (t- torch.min(t)) / (torch.max(t) - torch.min(t))

In [15]:
t

tensor([[0.2650, 0.0874, 0.6351, 0.5358, 0.9604, 0.7520, 0.0675],
        [0.8326, 0.4687, 0.9687, 0.8186, 0.4922, 0.0000, 0.2664],
        [0.8406, 0.6364, 0.3915, 0.2740, 0.9439, 1.0000, 0.6475],
        [0.6113, 0.7231, 0.0146, 0.5761, 0.1903, 0.6675, 0.9651]])

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [16]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))

In [17]:
ar1

tensor([[3, 7, 3, 3, 7, 4, 1],
        [6, 2, 5, 7, 6, 1, 9],
        [7, 4, 4, 4, 4, 8, 5],
        [7, 7, 0, 8, 5, 4, 3]])

In [18]:
ar2

tensor([[9, 3, 7, 5, 7, 4, 5],
        [3, 4, 2, 9, 0, 5, 8],
        [4, 0, 1, 6, 4, 3, 2],
        [6, 0, 1, 8, 9, 2, 5]])

In [19]:
torch.where(ar1 > ar2, ar1, ar2)

tensor([[9, 7, 7, 5, 7, 4, 5],
        [6, 4, 5, 9, 6, 5, 9],
        [7, 4, 4, 6, 4, 8, 5],
        [7, 7, 1, 8, 9, 4, 5]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [20]:
t = torch.randint(0, 100, (1, 20))

In [21]:
t

tensor([[31, 25, 31, 87, 82, 30, 47, 41, 52, 47, 74,  3, 19, 88, 51, 14, 88, 71,
         98, 31]])

In [22]:
torch.argmax(t[t != torch.max(t)])

tensor(13)

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [23]:
torch.Tensor([[i + j * 10 for i in range(1, 8)] for j in range(11)])

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.],
        [ 41.,  42.,  43.,  44.,  45.,  46.,  47.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.],
        [ 81.,  82.,  83.,  84.,  85.,  86.,  87.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.],
        [101., 102., 103., 104., 105., 106., 107.]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [24]:
import numpy as np
a_2d = torch.from_numpy(np.array([[3,3,3],[4,4,4],[5,5,5]]))
b_1d = torch.from_numpy(np.array([1,2,3]).reshape(-1, 1))

In [25]:
a_2d - b_1d

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [26]:
a = torch.from_numpy(np.array([1,2,3,2,3,4,3,4,5,6]))
b = torch.from_numpy(np.array([7,2,10,2,7,4,9,4,9,8]))

In [27]:
(a == b).nonzero().squeeze()

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [28]:
t = torch.arange(9).view(3,3)

In [29]:
t

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [30]:
torch.flip(t, [0, 1])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [31]:
a = torch.from_numpy(np.array([2, 6, 1, 9, 10, 3, 27]))

In [32]:
a[(a >= 5) & (a <= 10)]

tensor([ 6,  9, 10], dtype=torch.int32)

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [33]:
t = torch.from_numpy(np.arange(9).reshape(3,3))

In [34]:
t

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)

In [35]:
torch.index_select(t, 1, torch.LongTensor([0,2,1]))

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]], dtype=torch.int32)

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [36]:
t = torch.randint(0, 10, (8, 10))
t

tensor([[4, 7, 2, 0, 5, 6, 5, 2, 9, 1],
        [4, 4, 8, 4, 8, 0, 9, 7, 9, 9],
        [3, 2, 2, 1, 9, 8, 7, 2, 0, 0],
        [5, 5, 1, 8, 0, 7, 2, 6, 7, 2],
        [9, 7, 3, 3, 9, 2, 5, 8, 1, 5],
        [6, 0, 2, 9, 4, 1, 2, 1, 4, 5],
        [9, 2, 4, 7, 1, 3, 8, 1, 4, 6],
        [1, 6, 0, 7, 0, 8, 8, 5, 2, 8]])

In [37]:
torch.argmax(t.sum(axis=1))

tensor(1)

In [38]:
t[torch.argmax(t.sum(axis=1))]

tensor([4, 4, 8, 4, 8, 0, 9, 7, 9, 9])

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [39]:
t = torch.randint(0, 100, (1, 20))
t

tensor([[ 6, 39, 71, 95, 69, 55, 84, 24, 82, 68, 25, 52,  5, 70, 43,  8, 83, 23,
         48,  5]])

In [40]:
t = torch.where(t >= 70, 70, t)
torch.where(t <= 30, 30, t)

tensor([[30, 39, 70, 70, 69, 55, 70, 30, 70, 68, 30, 52, 30, 70, 43, 30, 70, 30,
         48, 30]])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [41]:
t1 = torch.randint(0, 10, (30, 3))
t2 = torch.randint(0, 10, (30, 3))

In [42]:
t1[t1 > t2].sum()

tensor(280)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [43]:
t = torch.randint(0, 10, (20, 20))
t

tensor([[9, 5, 2, 6, 5, 4, 2, 5, 2, 0, 4, 1, 2, 9, 4, 9, 7, 4, 9, 7],
        [2, 6, 5, 7, 8, 1, 0, 8, 3, 0, 5, 6, 1, 2, 4, 1, 8, 9, 2, 9],
        [3, 5, 3, 7, 2, 7, 7, 8, 1, 3, 3, 9, 2, 2, 4, 0, 0, 9, 0, 0],
        [4, 2, 0, 9, 7, 6, 3, 4, 1, 6, 0, 8, 4, 0, 6, 5, 4, 2, 7, 8],
        [9, 9, 7, 7, 2, 3, 6, 0, 6, 7, 5, 5, 8, 7, 3, 2, 6, 5, 2, 4],
        [6, 8, 6, 8, 4, 1, 5, 2, 1, 6, 0, 5, 8, 4, 3, 0, 3, 3, 4, 9],
        [2, 2, 6, 8, 6, 7, 9, 7, 6, 3, 3, 1, 2, 1, 9, 5, 9, 6, 7, 0],
        [7, 1, 4, 8, 0, 9, 8, 6, 2, 9, 3, 8, 2, 6, 4, 3, 8, 7, 2, 3],
        [7, 5, 0, 1, 0, 1, 2, 5, 1, 6, 0, 9, 8, 6, 3, 0, 9, 6, 7, 5],
        [1, 9, 4, 8, 9, 3, 3, 4, 0, 2, 3, 9, 3, 9, 1, 0, 2, 7, 9, 3],
        [7, 9, 5, 8, 1, 6, 7, 2, 5, 7, 2, 1, 5, 7, 8, 3, 9, 2, 2, 7],
        [7, 9, 3, 5, 9, 0, 3, 6, 8, 3, 7, 4, 5, 5, 8, 5, 8, 5, 9, 5],
        [1, 0, 1, 3, 2, 3, 7, 2, 1, 4, 1, 2, 3, 2, 9, 0, 1, 2, 7, 4],
        [8, 4, 6, 7, 6, 8, 4, 3, 4, 9, 8, 5, 6, 7, 6, 3, 7, 7, 8, 6],
        [2, 9, 2, 8,

In [44]:
arr = torch.Tensor([t[i, i+1] for i in range(19)])
arr

tensor([5., 5., 7., 7., 3., 5., 7., 2., 6., 3., 1., 5., 2., 6., 5., 3., 5., 8.,
        4.])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [45]:
t1 = torch.randint(0, 10, (5, 10))
t2 = torch.randint(0, 10, (5, 10))
t1

tensor([[6, 7, 3, 8, 2, 8, 4, 2, 9, 4],
        [8, 2, 0, 2, 7, 7, 9, 7, 8, 7],
        [6, 6, 3, 0, 6, 0, 6, 0, 9, 0],
        [4, 1, 9, 9, 1, 6, 5, 2, 2, 0],
        [4, 4, 8, 3, 3, 1, 6, 5, 5, 5]])

In [46]:
t2

tensor([[8, 7, 7, 8, 0, 3, 4, 9, 7, 3],
        [3, 8, 6, 9, 2, 7, 2, 3, 8, 4],
        [8, 0, 8, 9, 4, 1, 4, 5, 5, 4],
        [1, 0, 4, 5, 5, 0, 4, 3, 5, 6],
        [1, 6, 8, 1, 5, 5, 6, 6, 7, 8]])

In [47]:
torch.where(t1 == t2, t1 * 2, t1)

tensor([[ 6, 14,  3, 16,  2,  8,  8,  2,  9,  4],
        [ 8,  2,  0,  2,  7, 14,  9,  7, 16,  7],
        [ 6,  6,  3,  0,  6,  0,  6,  0,  9,  0],
        [ 4,  1,  9,  9,  1,  6,  5,  2,  2,  0],
        [ 4,  4, 16,  3,  3,  1, 12,  5,  5,  5]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [48]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar3 = torch.randint(0, 10, (4, 7))
ar1

tensor([[1, 8, 2, 9, 0, 3, 8],
        [8, 9, 0, 8, 7, 8, 3],
        [6, 1, 4, 9, 6, 6, 0],
        [0, 4, 5, 2, 1, 8, 5]])

In [49]:
ar1 = torch.where(ar1 > ar2, 0, ar1)
ar1 = torch.where(ar1 < ar3, 0, ar1)
ar1

tensor([[0, 0, 0, 0, 0, 3, 0],
        [8, 0, 0, 8, 0, 0, 0],
        [0, 1, 0, 0, 6, 0, 0],
        [0, 0, 5, 0, 0, 0, 5]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [50]:
ar1 = torch.randint(0, 20, (20, 5))
ar1

tensor([[14,  8,  3,  4,  2],
        [ 4,  0, 13, 13,  7],
        [15,  7,  5,  4, 12],
        [13, 16, 13,  4, 14],
        [17, 19,  0,  7,  7],
        [11,  9, 15, 18, 16],
        [ 3, 17, 12, 19,  7],
        [10,  5, 13,  7,  3],
        [ 8, 18,  1, 15,  7],
        [ 4,  5,  3, 13, 17],
        [ 1, 15,  1, 16, 17],
        [ 7, 17,  0,  2, 16],
        [19,  8, 19, 10, 19],
        [ 7,  2,  5, 12, 19],
        [ 1,  8,  8, 18, 17],
        [10, 19,  9,  7,  7],
        [14,  9, 17, 18, 16],
        [16,  6,  6,  1, 10],
        [ 7, 18, 14,  6, 16],
        [13,  0, 12, 16,  2]])

In [51]:
_, indx = ar1.max(axis=1)

In [52]:
indx

tensor([0, 2, 0, 1, 1, 3, 3, 2, 1, 4, 4, 1, 0, 4, 3, 1, 3, 0, 1, 3])

In [53]:
from collections import Counter
dict(Counter(indx.numpy()))

{0: 4, 2: 2, 1: 6, 3: 5, 4: 3}

In [54]:
# столбцы 3 и 0

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [55]:
ar1 = torch.rand((4, 7))
ar1

tensor([[0.7083, 0.3186, 0.1067, 0.9306, 0.2159, 0.8569, 0.0790],
        [0.2676, 0.9803, 0.3362, 0.0688, 0.1126, 0.2664, 0.0079],
        [0.9695, 0.6786, 0.3720, 0.2418, 0.9101, 0.8218, 0.8739],
        [0.4112, 0.5176, 0.4250, 0.9470, 0.6393, 0.4448, 0.2458]])

In [56]:
ar1.argmax()

tensor(8)

In [57]:
indx = (ar1==torch.max(ar1)).nonzero()

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [58]:
import torch.nn.functional as F
def one_hot(t):
    return F.one_hot(t)

In [59]:
one_hot(torch.tensor([2, 3, 2, 2, 2, 1]))

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [60]:
arr = torch.randint(0, 100, (1, 20))
arr

tensor([[42, 98, 11, 69, 24,  1, 40, 56, 20, 78, 40, 22, 47, 91, 93, 79, 66, 12,
         68, 68]])

In [61]:
m, _ = arr[0].mode()

In [62]:
arr[arr == m]

tensor([40, 40])

In [63]:
(arr==m).nonzero()

tensor([[ 0,  6],
        [ 0, 10]])

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [64]:
x = torch.linspace(0, 10, 100)
x * torch.sin(x)

tensor([ 0.0000,  0.0102,  0.0405,  0.0904,  0.1588,  0.2444,  0.3452,  0.4593,
         0.5842,  0.7172,  0.8554,  0.9958,  1.1350,  1.2698,  1.3968,  1.5128,
         1.6145,  1.6988,  1.7628,  1.8039,  1.8196,  1.8079,  1.7672,  1.6960,
         1.5937,  1.4597,  1.2943,  1.0979,  0.8717,  0.6172,  0.3365,  0.0322,
        -0.2929, -0.6352, -0.9911, -1.3564, -1.7267, -2.0972, -2.4633, -2.8199,
        -3.1620, -3.4845, -3.7825, -4.0511, -4.2859, -4.4823, -4.6364, -4.7446,
        -4.8037, -4.8110, -4.7646, -4.6628, -4.5048, -4.2904, -4.0201, -3.6950,
        -3.3171, -2.8888, -2.4135, -1.8950, -1.3379, -0.7472, -0.1287,  0.5114,
         1.1667,  1.8300,  2.4943,  3.1521,  3.7958,  4.4177,  5.0103,  5.5663,
         6.0784,  6.5396,  6.9437,  7.2844,  7.5565,  7.7552,  7.8764,  7.9167,
         7.8738,  7.7461,  7.5328,  7.2342,  6.8517,  6.3872,  5.8440,  5.2262,
         4.5387,  3.7874,  2.9791,  2.1211,  1.2217,  0.2896, -0.6657, -1.6346,
        -2.6070, -3.5723, -4.5202, -5.44

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [65]:
primes = torch.ones(100)
for p in range(2, 100):
    primes[2*p::p] = 0
primes = np.arange(100)[primes == 1.][2:]  
primes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [66]:
def e_dist(t1, t2):
    square = torch.square(t1 - t2)
    sum_square = torch.sum(square)
    return torch.sqrt(sum_square)

In [67]:
e_dist(torch.tensor((1, 2, 3)), torch.tensor((5, 5, 5)))

tensor(5.3852)

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [68]:
arr = torch.randint(0, 100, (20, 3))
arr

tensor([[29, 60, 31],
        [53, 99, 74],
        [99, 26, 39],
        [54, 12, 27],
        [29, 39, 54],
        [57, 33, 58],
        [59, 24, 20],
        [79, 30, 66],
        [24, 24, 96],
        [13, 31, 25],
        [70, 72, 99],
        [95, 67, 67],
        [89, 34, 80],
        [ 4, 10, 33],
        [12, 99,  1],
        [ 1, 14, 81],
        [44, 98, 83],
        [84,  6, 92],
        [30, 78, 53],
        [62, 18, 27]])

In [69]:
sort, indices = torch.sort(torch.sqrt(torch.sum(torch.square(arr), axis=1)))

In [70]:
arr[indices]

tensor([[ 4, 10, 33],
        [13, 31, 25],
        [54, 12, 27],
        [59, 24, 20],
        [62, 18, 27],
        [29, 39, 54],
        [29, 60, 31],
        [ 1, 14, 81],
        [57, 33, 58],
        [30, 78, 53],
        [12, 99,  1],
        [24, 24, 96],
        [79, 30, 66],
        [99, 26, 39],
        [89, 34, 80],
        [84,  6, 92],
        [95, 67, 67],
        [53, 99, 74],
        [44, 98, 83],
        [70, 72, 99]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [71]:
t = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
def func(t):
    s = [i for i in range(1, len(t)-1) if (t[i] > t[i+1]) and (t[i] > t[i-1])]
    return torch.tensor(s)

In [72]:
func(t)

tensor([2, 5])

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [73]:
arr = np.random.rand(100)
num = 0.5

In [74]:
arr[np.argmin(abs(arr - num))]

0.49749594201295033

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 

In [75]:
t = torch.empty(200).normal_(mean=0, std=10)
t

tensor([-14.4412, -14.9124,   7.1257,   7.9426,  -6.6014, -11.4443,  -6.6941,
         -0.1680,   0.6251,  -5.7832,  -9.2324, -15.5185,   7.4449,   8.4562,
          8.8011,   3.7403,   8.0087, -13.2465, -20.8794,   1.5510,  -1.0465,
        -15.6271,   2.6002, -10.0194,   7.5720,  -2.5025,  -1.6193, -15.6373,
         18.1745,   3.9888,  -4.7732,  12.6635,   5.3864, -13.5833,  -4.4397,
         -4.0485,  -3.5504, -11.7508,  -9.3413,  -1.3464,  -4.1704,  -2.3986,
          9.5323,   8.0581, -16.4661,   0.8314,   3.0939, -13.4878,   0.9122,
         -1.3885,  23.2987,  -1.4994,  -6.7582,   5.9175,   1.0332,  -8.4983,
          6.8683, -12.1813,   2.9414, -13.2875,  -1.5103,  17.7771,   9.8941,
         14.4845,   9.1656,   7.8342,   5.1590,  13.7916,  -2.0775,  11.1208,
         -4.3110,  11.3785,   2.3491,  -5.5235,   5.6061,   8.4652, -11.1116,
         -7.6945,   4.0703, -14.9799,  25.0274, -11.2391,  -7.3617,   5.0217,
         25.5330,   1.5424,  -5.3994,  -9.0146,   9.9015,   5.23

In [76]:
# import seaborn as sns
# sns.kdeplot(t.numpy().tolist())